### PR TITLE
cleanup basic auth w. go 1.4

### PR DESCRIPTION
**Pull request by csquared**

### CODE REVIEW

**Comment by ddollar** [comment]
Is BasicAuth in 1.4 or 1.5? I looked earlier and didn't see it in 1.4 but maybe I missed it

**Comment by csquared** [comment]
It worked for me w. 1.4, but I'm having a tough time finding the go stdlib docs of a specific version

**Comment by ddollar** [comment]
needs a rebase

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;X9hk9CIl&#x2F;121-clean-up-basic-auth"> Clean up basic auth</a>

**Pull request closed without merging**
