### PR TITLE
installable kernel

### PR DESCRIPTION
**Pull request by ddollar**

### CODE REVIEW

**Comment by ddollar** [comment]
In order to install right now you need to go to `cmd/formation` and run `make upload`. Make sure your `aws` CLI is pointing at the right place.

After you do that, copy the ARN of the lambda function that is generated and use it for the `Kernel` parameter for `dist/staging.json`

**Comment by mattmanning** [comment]
@ddollar For sizable changes like this can you try to add some info in the pull request description? A high-level overview of the motivations for the change and how you're attempting to accomplish them can be very helpful. It's often hard (or at least time-consuming) to build that context just from commit messages and raw diffs. It's good to write that stuff down for posterity anyway.

**Comment by mattmanning** [comment]
:+1: to merge

**Comment by nzoschke** [comment]
Wow... For `make upload`, I needed to update my local tool chain:

* `brew reinstall go --with-cc-common`
* `pip install awscli --upgrade`

**Comment by nzoschke** [comment]
I am getting:

CREATE_FAILED	Custom::ECSCluster	Cluster	Failed to create resource. UnrecognizedClientException: The security token included in the request is invalid. status code: 400, request id: []

**Comment by nzoschke** [comment]
I see this in my lambda logs:

```
{
    "errorMessage": "Process exited with non-zero status code: 126",
    "errorType": "Error",
    "stackTrace": [
        "ChildProcess.<anonymous> (/var/task/lambda.js:17:27)",
        "ChildProcess.emit (events.js:98:17)",
        "maybeClose (child_process.js:756:16)",
        "Process.ChildProcess._handle.onexit (child_process.js:823:5)"
    ]
}
```

**Comment by nzoschke** [comment]
I am making progress now.

The first time I did `make upload` I didn't have the cross-compiler right. No subsequent `make uploads` seem to have fixed the `convox-formation` function.

I re-uploaded to a clean `cvx-formation` function and it is going better.

**Pull request merged**
